### PR TITLE
Reformat all comments using rustfmt

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Review by djeedai — APPROVED** [review]
Sorry for the delay. That looks good. Out of curiosity is there any specific config you used? I generally have VS Code auto-format all the time, so I'm surprised there's so many comments not formatted. Did you make some local changes to the rustfmt config?

**Comment by djeedai** [comment]
I'm getting no change at all with `cargo fmt --all`. How did you format those comments? Also, the README for `rustfmt` says it doesn't format comments : https://github.com/rust-lang/rustfmt

**Comment by SUPERCILEX** [comment]
Yeah, it's a nightly configuration: https://rust-lang.github.io/rustfmt/?version=master&search=wrap_c#wrap_comments.

**Comment by djeedai** [comment]
Can you please add the `rustfmt.toml` file to the PR, so others can replicate this? Even with [wrap_comments](https://rust-lang.github.io/rustfmt/?version=master&search=wrap_c#wrap_comments) I don't get the same result, seems there are other options you used, like moving the comment on the previous line if it's too long to be inline.

**Comment by djeedai** [comment]
Ah I guess I need also `unstable_features = true`, so some `rustfmt.toml` like:

```toml
unstable_features = true
wrap_comments=true
```

**Comment by SUPERCILEX** [comment]
Does unstable_features work?

I did have to manually edit the example comments and your right my rustfmt had an extra config for imports.

**Comment by SUPERCILEX** [comment]
Hmmm, I'm not sure CI is actually set up to check clippy or fmt. I get tons of errors:

```
$ cargo +stable fmt
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
```

**Comment by djeedai** [comment]
Ah yes obviously if we add some unstable feature to `rustfmt.toml` then it doesn't build anymore in stable... I wonder if we can pass those args on the command line for unstable CI only?

**Comment by djeedai** [comment]
> Does unstable_features work?
> 
> I did have to manually edit the example comments and your right my rustfmt had an extra config for imports.

Also yes the config I pasted worked for me without any additional settings. I upgraded Rust to latest first, then ran `cargo +nightly fmt --all` from the root of the repository. I didn't need the granularity thing.

**Pull request merged**
