### PR TITLE
Infinite mirrored repeats crash

### PR DESCRIPTION
**Pull request by SergioRibera**
I have seen that there was not a PR about it and I think it is something that had to be fixed, it turns out that if we have an infinite or repeated sequence there is a problem when calculating the remaining time, for this a solution was proposed [here](https://github.com/djeedai/bevy_tweening/issues/79#issuecomment-1383284902) and [here](https://github.com/sibsibsib/bevy_tweening/commit/97b5eac01b7472dec813e88c45e00556d646953c) was developed the implementation, apparently they had not opened a PR so here I am to propose the PR updated to the last commit of the main branch in the project

### CODE REVIEW

**Comment by djeedai** [comment]
Thanks for the contribution. Unfortunately I think this requires more discussion and an agreed plan of action first.

There's a number of issues with the implemented approach that I don't like.

1. The behavior is maybe useful in some cases, but is definitely unexpected. It's a mix between the `Sequence` and `Tracks` behaviors, which depends on top of that on other parameters. I'm afraid this will just confuse most users. Even the OP admits it "weird".

2. As explained in several other places, the issue is not to solve in isolation those individual issues; this is reasonably easy. The real issue is to design something consistent. And all the difficulty comes from other APIs ignored in most discussions. For example, what happens if the user jumps to a specific point in time with `set_elapsed()`? And do we trigger completion events in that case? What about playback in reverse direction?

I appreciate sequences with an infinite loop is a common use case several users asked for. But I have yet to hear about a reasonable design that 1) doesn't introduce unexpected behaviors, and 2) remains consistent across the various APIs available to manipulate the tweenable playback. I'm fine making concessions about having to raise a warning at runtime if the user crafts an unreasonable animation, if we can't find a way to prevent that by design at build time. But at least I want to prevent users from shooting themselves in the foot with an animation there's no clear mental model for; this would be the worst we can achieve here.

As a minor extra issue, the `progress`-based API is kind of deprecated, and shouldn't be used as the source of truth.
 It lacks precision over the `Duration`-based one, due to floating point. It can remain as a utility on top of the `Duration`-based one but we already worked to remove the use of `progress` internally, and this change undoes it.

**Comment by SergioRibera** [comment]
A perfect, indeed they are cases that are not contemplated in the implementation.

Is there a channel where this is being discussed? I would like to see and participate, maybe we can make this solution faster 😁

**Comment by djeedai** [comment]
The Discord channel for this crate is on Bevy's official server: https://discord.com/channels/691052431525675048/1036006196659900497

**Comment by djeedai** [comment]
I'm going to close this one, as I don't think there's consensus on the approach. Sorry about that :) Please feel free to reopen and argument if there's a strong opinion that this is indeed the best approach, and why?

**Pull request closed without merging**
