### PR TITLE
Fix loss of precision in AnimClock and improve performance

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Old:

1s 320ms
Left:  140292640
Right: 140292630

New:

759ms
Success

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Oh, for whatever reason now I'm seeing ~1s time for the old version. The new one is still faster, but not by as much I guess.

**Comment by djeedai** [comment]
If you want stable results you need to `bench` it. This test is not warming the codepath before measuring, so will have variations per run. An ideal perf test runs the code first a few times so that all caches are hot and the CPU frequency scaling if any is already in power/perf mode (and ideally disables low-power and frequency scaling, but that's not always possible). That's probably good enough though given the large difference before/after.

**Comment by SUPERCILEX** [comment]
Yeah, I'm being very lazy. I mainly just wanted to check that using u128s wasn't slower than the old stuff.

**Comment by djeedai** [comment]
I'm going to merge as is for now, but I think the removal of `times_completed` will have to be reverted for #16 to work. Anyway, we'll see.

**Review by djeedai — APPROVED** [review]

**Comment by SUPERCILEX** [comment]
Sounds good! I don't have time this week, but I'll start working on your ideas for https://github.com/djeedai/bevy_tweening/pull/19 (unless you get to it first :smile:) which will let me see what's still applicable in https://github.com/djeedai/bevy_tweening/pull/21.

**Pull request merged**
